INSERT INTO public.events (id, title, place, maps_url, image_url, is_featured, is_free, 
      starts_at, city_id, category_id, status, description, image_alignment) VALUES ('6e7db010-4f1c-4e09-884e-f26b1a6e6a65',
      'Futsal: CD Virgili Cádiz vs CD Alcalá',
      'Complejo Deportivo Ciudad de Cádiz, Cádiz',
      'https://www.google.com/maps/search/?api=1&query=Complejo+Deportivo+Ciudad+de+Cadiz',
      'https://oudofaiekedtaovrdqeo.supabase.co/storage/v1/object/public/sample-images/1/3/13.webp',
      FALSE,
      FALSE,
      '2026-01-17T18:00:00Z'::timestamptz,
      (SELECT id FROM public.cities WHERE LOWER(name) = LOWER('Cádiz') LIMIT 1),
      (SELECT id FROM public.categories WHERE LOWER(slug) = 'deportes' LIMIT 1),
      'published',
      'Segunda División B Futsal. Partido clave para los gaditanos en casa.',
      'center');
INSERT INTO public.events (id, title, place, maps_url, image_url, is_featured, is_free, 
      starts_at, city_id, category_id, status, description, image_alignment) VALUES ('e0bd925b-2082-418c-bc81-33e6255a2e2b',
      'Fútbol Juvenil: Cádiz CF vs UD Maracena',
      'Ciudad Deportiva Bahía de Cádiz (El Rosal), Puerto Real',
      'https://www.google.com/maps/search/?api=1&query=Ciudad+Deportiva+Bahia+de+Cadiz',
      'https://oudofaiekedtaovrdqeo.supabase.co/storage/v1/object/public/sample-images/1/3/02.webp',
      FALSE,
      TRUE,
      '2026-01-24T12:00:00Z'::timestamptz,
      (SELECT id FROM public.cities WHERE LOWER(name) = LOWER('Puerto Real') LIMIT 1),
      (SELECT id FROM public.categories WHERE LOWER(slug) = 'deportes' LIMIT 1),
      'published',
      'División de Honor Juvenil (Grupo 4). Las futuras estrellas del Cádiz.',
      'center');
INSERT INTO public.events (id, title, place, maps_url, image_url, is_featured, is_free, 
      starts_at, city_id, category_id, status, description, image_alignment) VALUES ('c5b4a995-d27a-4aef-9a21-a1be1a4ba59e',
      'Fútbol Alevín: Cádiz CF ''B'' vs Divina Pastora',
      'Ciudad Deportiva Bahía de Cádiz (El Rosal), Puerto Real',
      'https://www.google.com/maps/search/?api=1&query=Ciudad+Deportiva+Bahia+de+Cadiz',
      'https://oudofaiekedtaovrdqeo.supabase.co/storage/v1/object/public/sample-images/1/3/05.webp',
      FALSE,
      TRUE,
      '2026-01-24T10:30:00Z'::timestamptz,
      (SELECT id FROM public.cities WHERE LOWER(name) = LOWER('Puerto Real') LIMIT 1),
      (SELECT id FROM public.categories WHERE LOWER(slug) = 'deportes' LIMIT 1),
      'published',
      '2ª Andaluza Alevín. Duelo de canteras provinciales.',
      'center');
INSERT INTO public.events (id, title, place, maps_url, image_url, is_featured, is_free, 
      starts_at, city_id, category_id, status, description, image_alignment) VALUES ('923d983f-5561-4be0-81db-b9d9cb7f8346',
      'Fútbol Infantil: Cádiz CF ''B'' vs Xerez Deportivo FC',
      'Ciudad Deportiva Bahía de Cádiz (El Rosal), Puerto Real',
      'https://www.google.com/maps/search/?api=1&query=Ciudad+Deportiva+Bahia+de+Cadiz',
      'https://oudofaiekedtaovrdqeo.supabase.co/storage/v1/object/public/sample-images/1/3/16.webp',
      FALSE,
      TRUE,
      '2026-01-24T16:00:00Z'::timestamptz,
      (SELECT id FROM public.cities WHERE LOWER(name) = LOWER('Puerto Real') LIMIT 1),
      (SELECT id FROM public.categories WHERE LOWER(slug) = 'deportes' LIMIT 1),
      'published',
      '1ª Andaluza Infantil. Derbi de canteras gaditanas.',
      'center');
INSERT INTO public.events (id, title, place, maps_url, image_url, is_featured, is_free, 
      starts_at, city_id, category_id, status, description, image_alignment) VALUES ('f13e1fee-e024-49f8-9bff-efb0f45c7742',
      'Fútbol Infantil: Cádiz CF ''A'' vs SAM-CAM Dos Hermanas',
      'Ciudad Deportiva Bahía de Cádiz (El Rosal), Puerto Real',
      'https://www.google.com/maps/search/?api=1&query=Ciudad+Deportiva+Bahia+de+Cadiz',
      'https://oudofaiekedtaovrdqeo.supabase.co/storage/v1/object/public/sample-images/1/3/14.webp',
      FALSE,
      TRUE,
      '2026-01-25T12:30:00Z'::timestamptz,
      (SELECT id FROM public.cities WHERE LOWER(name) = LOWER('Puerto Real') LIMIT 1),
      (SELECT id FROM public.categories WHERE LOWER(slug) = 'deportes' LIMIT 1),
      'published',
      'División de Honor Infantil. Máxima categoría infantil autonómica.',
      'center');
INSERT INTO public.events (id, title, place, maps_url, image_url, is_featured, is_free, 
      starts_at, city_id, category_id, status, description, image_alignment) VALUES ('2977f9dd-dff7-432a-a42a-29393ea6258b',
      'Copa del Rey Juvenil: Octavos de Final',
      'Ciudad Deportiva Bahía de Cádiz (El Rosal), Puerto Real',
      'https://www.google.com/maps/search/?api=1&query=Ciudad+Deportiva+Bahia+de+Cadiz',
      'https://oudofaiekedtaovrdqeo.supabase.co/storage/v1/object/public/sample-images/1/3/10.webp',
      FALSE,
      FALSE,
      '2026-01-28T19:00:00Z'::timestamptz,
      (SELECT id FROM public.cities WHERE LOWER(name) = LOWER('Puerto Real') LIMIT 1),
      (SELECT id FROM public.categories WHERE LOWER(slug) = 'deportes' LIMIT 1),
      'published',
      'Posible partido del Cádiz CF Juvenil (Pendiente de sorteo y clasificación definitiva).',
      'center');
INSERT INTO public.events (id, title, place, maps_url, image_url, is_featured, is_free, 
      starts_at, city_id, category_id, status, description, image_alignment) VALUES ('7e0b3f03-943f-4d78-b9a0-0f773d3040ce',
      'Futsal: CD Virgili Cádiz vs UD Alchoyano',
      'Complejo Deportivo Ciudad de Cádiz, Cádiz',
      'https://www.google.com/maps/search/?api=1&query=Complejo+Deportivo+Ciudad+de+Cadiz',
      'https://oudofaiekedtaovrdqeo.supabase.co/storage/v1/object/public/sample-images/1/3/04.webp',
      FALSE,
      FALSE,
      '2026-01-31T18:00:00Z'::timestamptz,
      (SELECT id FROM public.cities WHERE LOWER(name) = LOWER('Cádiz') LIMIT 1),
      (SELECT id FROM public.categories WHERE LOWER(slug) = 'deportes' LIMIT 1),
      'published',
      'Segunda División B Futsal.',
      'center');
INSERT INTO public.events (id, title, place, maps_url, image_url, is_featured, is_free, 
      starts_at, city_id, category_id, status, description, image_alignment) VALUES ('ce4c3005-673b-4eb0-9dbe-a93b6496f2cb',
      'Fútbol Juvenil: Cádiz CF vs Arenas de Armilla',
      'Ciudad Deportiva Bahía de Cádiz (El Rosal), Puerto Real',
      'https://www.google.com/maps/search/?api=1&query=Ciudad+Deportiva+Bahia+de+Cadiz',
      'https://oudofaiekedtaovrdqeo.supabase.co/storage/v1/object/public/sample-images/1/3/08.webp',
      FALSE,
      TRUE,
      '2026-02-08T12:00:00Z'::timestamptz,
      (SELECT id FROM public.cities WHERE LOWER(name) = LOWER('Puerto Real') LIMIT 1),
      (SELECT id FROM public.categories WHERE LOWER(slug) = 'deportes' LIMIT 1),
      'published',
      'División de Honor Juvenil (Grupo 4).',
      'center');
INSERT INTO public.events (id, title, place, maps_url, image_url, is_featured, is_free, 
      starts_at, city_id, category_id, status, description, image_alignment) VALUES ('ca6e7dae-7d90-46c4-a664-6766b23fe3b4',
      'Futsal: CD Virgili Cádiz vs Joasan Construcciones',
      'Complejo Deportivo Ciudad de Cádiz, Cádiz',
      'https://www.google.com/maps/search/?api=1&query=Complejo+Deportivo+Ciudad+de+Cadiz',
      'https://oudofaiekedtaovrdqeo.supabase.co/storage/v1/object/public/sample-images/1/3/12.webp',
      FALSE,
      FALSE,
      '2026-02-14T18:00:00Z'::timestamptz,
      (SELECT id FROM public.cities WHERE LOWER(name) = LOWER('Cádiz') LIMIT 1),
      (SELECT id FROM public.categories WHERE LOWER(slug) = 'deportes' LIMIT 1),
      'published',
      'Segunda División B Futsal.',
      'center');
INSERT INTO public.events (id, title, place, maps_url, image_url, is_featured, is_free, 
      starts_at, city_id, category_id, status, description, image_alignment) VALUES ('e08c8b62-82ca-4548-a8ad-c80762064fbe',
      'Fútbol Juvenil: Cádiz CF vs UD Tomares',
      'Ciudad Deportiva Bahía de Cádiz (El Rosal), Puerto Real',
      'https://www.google.com/maps/search/?api=1&query=Ciudad+Deportiva+Bahia+de+Cadiz',
      'https://oudofaiekedtaovrdqeo.supabase.co/storage/v1/object/public/sample-images/1/3/06.webp',
      FALSE,
      TRUE,
      '2026-02-15T12:00:00Z'::timestamptz,
      (SELECT id FROM public.cities WHERE LOWER(name) = LOWER('Puerto Real') LIMIT 1),
      (SELECT id FROM public.categories WHERE LOWER(slug) = 'deportes' LIMIT 1),
      'published',
      'División de Honor Juvenil (Grupo 4).',
      'center');
INSERT INTO public.events (id, title, place, maps_url, image_url, is_featured, is_free, 
      starts_at, city_id, category_id, status, description, image_alignment) VALUES ('eeda09b3-ad9f-408f-9c1c-875ae3940f00',
      'Fútbol Infantil: Cádiz CF ''A'' vs Real Betis',
      'Ciudad Deportiva Bahía de Cádiz (El Rosal), Puerto Real',
      'https://www.google.com/maps/search/?api=1&query=Ciudad+Deportiva+Bahia+de+Cadiz',
      'https://oudofaiekedtaovrdqeo.supabase.co/storage/v1/object/public/sample-images/1/3/15.webp',
      FALSE,
      TRUE,
      '2026-02-15T11:00:00Z'::timestamptz,
      (SELECT id FROM public.cities WHERE LOWER(name) = LOWER('Puerto Real') LIMIT 1),
      (SELECT id FROM public.categories WHERE LOWER(slug) = 'deportes' LIMIT 1),
      'published',
      'División de Honor Infantil. Partidazo contra uno de los mejores equipos de Andalucía.',
      'center');
INSERT INTO public.events (id, title, place, maps_url, image_url, is_featured, is_free, 
      starts_at, city_id, category_id, status, description, image_alignment) VALUES ('e1ed1880-b783-4065-92a1-c5ac5181ba5b',
      'DERBI Futsal: CD Virgili Cádiz vs Xerez Toyota Nimauto',
      'Complejo Deportivo Ciudad de Cádiz, Cádiz',
      'https://www.google.com/maps/search/?api=1&query=Complejo+Deportivo+Ciudad+de+Cadiz',
      'https://oudofaiekedtaovrdqeo.supabase.co/storage/v1/object/public/sample-images/1/3/04.webp',
      FALSE,
      FALSE,
      '2026-02-21T18:30:00Z'::timestamptz,
      (SELECT id FROM public.cities WHERE LOWER(name) = LOWER('Cádiz') LIMIT 1),
      (SELECT id FROM public.categories WHERE LOWER(slug) = 'deportes' LIMIT 1),
      'published',
      'Segunda División B Futsal. El gran derbi provincial de fútbol sala.',
      'center');